export const MOCK_MOVIES = [
  {
    id: "mock-1",
    slug: "dune-part-two",
    title: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    genres: ["Sci-Fi", "Adventure", "Action"],
    seoTitle: "Dune: Part Two (2024)",
  },
  {
    id: "mock-2",
    slug: "oppenheimer",
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    genres: ["Drama", "History", "Thriller"],
    seoTitle: "Oppenheimer",
  },
  {
    id: "mock-3",
    slug: "interstellar",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    seoTitle: "Interstellar",
  },
  {
    id: "mock-4",
    slug: "blade-runner-2049",
    title: "Blade Runner 2049",
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    genres: ["Action", "Sci-Fi", "Thriller"],
    seoTitle: "Blade Runner 2049",
  },
  {
    id: "mock-5",
    slug: "the-dark-knight",
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genres: ["Action", "Crime", "Drama"],
    seoTitle: "The Dark Knight",
  },
  {
    id: "mock-6",
    slug: "inception",
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    seoTitle: "Inception",
  },
  {
    id: "mock-7",
    slug: "spider-man-across-the-spider-verse",
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    genres: ["Animation", "Action", "Adventure"],
    seoTitle: "Spider-Man: Across the Spider-Verse",
  },
  {
    id: "mock-8",
    slug: "everything-everywhere-all-at-once",
    title: "Everything Everywhere All at Once",
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.",
    genres: ["Action", "Adventure", "Comedy"],
    seoTitle: "Everything Everywhere All at Once",
  },
  {
    id: "mock-9",
    slug: "parasite",
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    genres: ["Drama", "Thriller"],
    seoTitle: "Parasite",
  },
  {
    id: "mock-10",
    slug: "the-matrix",
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    genres: ["Action", "Sci-Fi"],
    seoTitle: "The Matrix",
  },
  {
    id: "mock-11",
    slug: "gladiator",
    title: "Gladiator",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    genres: ["Action", "Adventure", "Drama"],
    seoTitle: "Gladiator",
  },
  {
    id: "mock-12",
    slug: "arrival",
    title: "Arrival",
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    genres: ["Drama", "Sci-Fi"],
    seoTitle: "Arrival",
  },
  {
    id: "mock-13",
    slug: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    seoTitle: "Mad Max: Fury Road",
  },
  {
    id: "mock-14",
    slug: "the-lord-of-the-rings",
    title: "The Return of the King",
    description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    genres: ["Action", "Adventure", "Drama"],
    seoTitle: "The Return of the King",
  },
  {
    id: "mock-15",
    slug: "avengers-endgame",
    title: "Avengers: Endgame",
    description: "After the devastating events of Infinity War, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    genres: ["Action", "Adventure", "Drama"],
    seoTitle: "Avengers: Endgame",
  },
  {
    id: "mock-16",
    slug: "john-wick-4",
    title: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.",
    genres: ["Action", "Crime", "Thriller"],
    seoTitle: "John Wick: Chapter 4",
  },
  {
    id: "mock-17",
    slug: "the-batman",
    title: "The Batman",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    genres: ["Action", "Crime", "Drama"],
    seoTitle: "The Batman",
  },
  {
    id: "mock-18",
    slug: "top-gun-maverick",
    title: "Top Gun: Maverick",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite.",
    genres: ["Action", "Drama"],
    seoTitle: "Top Gun: Maverick",
  }
];

export const MOCK_SERIES = [
  {
    id: "series-1",
    slug: "succession",
    title: "Succession",
    description: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.",
    genres: ["Drama", "Comedy"],
    seoTitle: "Succession",
  },
  {
    id: "series-2",
    slug: "the-last-of-us",
    title: "The Last of Us",
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    genres: ["Action", "Drama", "Sci-Fi"],
    seoTitle: "The Last of Us",
  },
  {
    id: "series-3",
    slug: "stranger-things",
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    genres: ["Sci-Fi", "Horror", "Drama"],
    seoTitle: "Stranger Things",
  },
  {
    id: "series-4",
    slug: "house-of-the-dragon",
    title: "House of the Dragon",
    description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
    genres: ["Action", "Adventure", "Drama"],
    seoTitle: "House of the Dragon",
  },
  {
    id: "series-5",
    slug: "severance",
    title: "Severance",
    description: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    seoTitle: "Severance",
  },
  {
    id: "series-6",
    slug: "the-bear",
    title: "The Bear",
    description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.",
    genres: ["Comedy", "Drama"],
    seoTitle: "The Bear",
  },
  {
    id: "series-7",
    slug: "breaking-bad",
    title: "Breaking Bad",
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    genres: ["Crime", "Drama", "Thriller"],
    seoTitle: "Breaking Bad",
  },
  {
    id: "series-8",
    slug: "true-detective",
    title: "True Detective",
    description: "Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved.",
    genres: ["Crime", "Drama", "Mystery"],
    seoTitle: "True Detective",
  },
  {
    id: "series-9",
    slug: "the-wire",
    title: "The Wire",
    description: "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
    genres: ["Crime", "Drama", "Thriller"],
    seoTitle: "The Wire",
  },
  {
    id: "series-10",
    slug: "game-of-thrones",
    title: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    genres: ["Action", "Adventure", "Drama"],
    seoTitle: "Game of Thrones",
  }
];

